name: Flutter CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      
  build-android:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      # Create a dummy api_keys.dart file for CI builds
      - run: |
          mkdir -p lib/config
          echo "class ApiKeys { static const String youtubeApiKey = 'dummy_key_for_ci'; }" > lib/config/api_keys.dart
      - run: flutter build apk --debug 